### ISSUE TITLE
F-Droid build

### ISSUE THREAD

**Issue by SebastianSchildt** [eclipse-kuksa/kuksa-android-companion#5]
**Is your feature request related to a problem? Please describe.**
As this is an awesome toy to play with and experience KUKSA databroker, it would be good, if it also where accessible for people who are not interested in coding/compiling for Android

**Describe the solution you'd like**
Have an APK available in a free App Store. I'd suggest FDroid following the procedure described under "submit via F-Droid Data repository" https://f-droid.org/en/contribute/

**Describe alternatives you've considered**
We may just publish an APK artefact, once our CI is able to spit one out. F-Droid would be cooler

**Comment by wba2hi** [comment]
RFP: https://gitlab.com/fdroid/rfp/-/issues/2637
Merge Request: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14395

**Comment by wba2hi** [comment]
Merge Request was merged. 

https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-long-does-it-take-for-my-app-to-show-up-on-website-and-client
According to the article it might take 3 - 7 days until the app appears in the F-Droid store.

Keeping the ticket open until we can find it there.

**Comment by SebastianSchildt** [comment]
Closing this, it is published: https://f-droid.org/en/packages/org.eclipse.kuksa.companion/
