### ISSUE TITLE
Replace ConnectionStatusBar by something more subtle

### ISSUE THREAD

**Issue by wba2hi** [eclipse-kuksa/kuksa-android-companion#58]
**Is your feature request related to a problem? Please describe.**
Limited Display Space.

**Describe the solution you'd like**
ConnectionStatusBar is to big and should be replaced by something less obstrusive. See discussion here: https://github.com/eclipse-kuksa/kuksa-android-companion/issues/56

**Describe alternatives you've considered**
None

**Additional context**
None

Solution Ideas:
- only show ConnectionStatusBar when disconnected / remove ConnectionStatusBar when connected 
-- unfortunately RamsesView can only shrink in size and not expand, instead of expanding it will add a black area. This needs to be workarounded
- use a FloatingActionButtion (which is only visible while disconnected)
-- In Landscape Mode a FloatingActionButton is added to the bottom right side of the screen to open the SideSheet. This should be kept in mind when adding additional FloatingActionButtons so they don't overlap.
- ... other solution

**Comment by Chrylo** [comment]
I like the first idea. To only have the status bar when disconnected. How about moving the bar to the bottom of the Navigation bar as an overlay of the Ramses view so it does not have to shrink / expand?
